[project]
name = "mas-llm-workshop-25"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "bpy==4.4.0",
    "logfire>=4.14.2",
    "numpy==1.26.4",
    "pandas>=2.3.3",
    "pydantic-ai-slim[openai]~=1.11.0",
    "python-dotenv>=1.2.1",
]
